<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="12.0410" tests="10" failures="8">
  <testsuite name="Root Suite" timestamp="2021-12-02T01:40:41" tests="0" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="express_authentication" timestamp="2021-12-02T01:40:41" tests="7" file="F:\Repos\proyect\test\index.spec.js" time="6.0220" failures="3">
    <testcase name="express_authentication Should generate an API key and add it to file" time="2.0110" classname="Should generate an API key and add it to file">
      <failure message="Timeout of 2000ms exceeded. For async tests and hooks, ensure &quot;done()&quot; is called; if returning a Promise, ensure it resolves. (F:\Repos\proyect\test\index.spec.js)" type="Error"><![CDATA[Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (F:\Repos\proyect\test\index.spec.js)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)]]></failure>
    </testcase>
    <testcase name="express_authentication &quot;before each&quot; hook for &quot;Should generate 5 unique API Keys&quot;" time="2.0040" classname="&quot;before each&quot; hook for &quot;Should generate 5 unique API Keys&quot;">
      <failure message="Timeout of 2000ms exceeded. For async tests and hooks, ensure &quot;done()&quot; is called; if returning a Promise, ensure it resolves. (F:\Repos\proyect\test\index.spec.js)" type="Error"><![CDATA[Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (F:\Repos\proyect\test\index.spec.js)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)]]></failure>
    </testcase>
    <testcase name="express_authentication &quot;after each&quot; hook for &quot;Should generate 5 unique API Keys&quot;" time="2.0070" classname="&quot;after each&quot; hook for &quot;Should generate 5 unique API Keys&quot;">
      <failure message="Timeout of 2000ms exceeded. For async tests and hooks, ensure &quot;done()&quot; is called; if returning a Promise, ensure it resolves. (F:\Repos\proyect\test\index.spec.js)" type="Error"><![CDATA[Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (F:\Repos\proyect\test\index.spec.js)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)]]></failure>
    </testcase>
  </testsuite>
  <testsuite name="payment check" timestamp="2021-12-02T01:40:47" tests="3" file="F:\Repos\proyect\test\payment.spec.js" time="6.0190" failures="5">
    <testcase name="payment check Should generate an random price" time="2.0070" classname="Should generate an random price">
      <failure message="Timeout of 2000ms exceeded. For async tests and hooks, ensure &quot;done()&quot; is called; if returning a Promise, ensure it resolves. (F:\Repos\proyect\test\payment.spec.js)" type="Error"><![CDATA[Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (F:\Repos\proyect\test\payment.spec.js)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)]]></failure>
    </testcase>
    <testcase name="payment check &quot;after each&quot; hook for &quot;Should generate 5 random prices&quot;" time="0.0000" classname="&quot;after each&quot; hook for &quot;Should generate 5 random prices&quot;">
      <failure message="done() called multiple times" type="Error"><![CDATA[Error: done() called multiple times
    at F:\Repos\proyect\test\payment.spec.js:35:23]]></failure>
    </testcase>
    <testcase name="payment check Should generate 5 random prices" time="2.0050" classname="Should generate 5 random prices">
      <failure message="Timeout of 2000ms exceeded. For async tests and hooks, ensure &quot;done()&quot; is called; if returning a Promise, ensure it resolves. (F:\Repos\proyect\test\payment.spec.js)" type="Error"><![CDATA[Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (F:\Repos\proyect\test\payment.spec.js)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)]]></failure>
    </testcase>
    <testcase name="payment check &quot;after each&quot; hook for &quot;Should return 5 promo codes&quot;" time="0.0000" classname="&quot;after each&quot; hook for &quot;Should return 5 promo codes&quot;">
      <failure message="done() called multiple times" type="Error"><![CDATA[Error: done() called multiple times
    at F:\Repos\proyect\test\payment.spec.js:35:23]]></failure>
    </testcase>
    <testcase name="payment check Should return 5 promo codes" time="2.0070" classname="Should return 5 promo codes">
      <failure message="Timeout of 2000ms exceeded. For async tests and hooks, ensure &quot;done()&quot; is called; if returning a Promise, ensure it resolves. (F:\Repos\proyect\test\payment.spec.js)" type="Error"><![CDATA[Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (F:\Repos\proyect\test\payment.spec.js)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)]]></failure>
    </testcase>
  </testsuite>
</testsuites>